[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.advidevops.online

[frontend]
roboshop-dev.advidevops.online

[redis]
localhost

[user]
user-dev.advidevops.online

[cart]
cart-dev.advidevops.online

[mysql]
mysql-dev.advidevops.online

[shipping]
shipping-dev.advidevops.online

[rabbitmq]
rabbitmq-dev.advidevops.online

[payment]
payment-dev.advidevops.online

