[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[frontend]
roboshop-dev.advidevops.online

[redis]
localhost

[user]
user-dev.advidevops.online

[cart]
cart-dev.advidevops.online

[mysql]
localhost

[shipping]
shipping-dev.advidevops.online

[rabbitmq]
localhost

[payment]
payment-dev.advidevops.online

